#!/bin/bash

# 双平台同步部署脚本
# 自动部署到 Vercel + Gitee Pages

set -e

PROJECT_DIR="/data1/cc/vide-coding/ai-news-hub"
cd "$PROJECT_DIR"

echo "=========================================="
echo "  双平台同步部署开始"
echo "=========================================="
echo "时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# 1. 检查是否有未提交的更改
echo -e "${BLUE}[1/6] 检查 Git 状态...${NC}"
if [ -n "$(git status --porcelain)" ]; then
    echo -e "${YELLOW}⚠️  有未提交的更改，请先提交${NC}"
    git status --short
    exit 1
fi
echo -e "${GREEN}✓ Git 工作区干净${NC}"
echo ""

# 2. 拉取最新代码
echo -e "${BLUE}[2/6] 拉取最新代码...${NC}"
git fetch --all
git pull origin main
echo -e "${GREEN}✓ 代码已更新${NC}"
echo ""

# 3. 安装依赖
echo -e "${BLUE}[3/6] 安装项目依赖...${NC}"
npm install
echo -e "${GREEN}✓ 依赖安装完成${NC}"
echo ""

# 4. 构建项目
echo -e "${BLUE}[4/6] 构建 VitePress 网站...${NC}"
npm run docs:build

if [ ! -d "docs/.vitepress/dist" ]; then
    echo -e "${RED}❌ 构建失败：dist 目录不存在${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 网站构建完成${NC}"
echo ""

# 5. 提交构建产物
echo -e "${BLUE}[5/6] 提交构建产物到 Git...${NC}"
git add docs/.vitepress/dist/

# 检查是否有新的构建产物
if git diff --cached --quiet; then
    echo -e "${YELLOW}⚠️  没有新的构建产物，跳过提交${NC}"
else
    git commit -m "Build: Auto-deploy - $(date '+%Y-%m-%d %H:%M:%S')

- VitePress build completed
- Sync to dual platform (Vercel + Gitee)
- Auto-generated by deploy-dual-platform.sh"

    echo -e "${GREEN}✓ 构建产物已提交${NC}"
fi
echo ""

# 6. 推送到双平台
echo -e "${BLUE}[6/6] 推送到双平台...${NC}"
echo ""

# 推送到 GitHub (Vercel)
echo -e "${YELLOW}→ 推送到 GitHub (Vercel 自动触发)...${NC}"
git push origin main
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ GitHub 推送成功${NC}"
    echo -e "   ${GREEN}→ Vercel 部署地址: https://ai-news-hub-rosy.vercel.app/${NC}"
else
    echo -e "${RED}✗ GitHub 推送失败${NC}"
fi
echo ""

# 推送到 Gitee (Gitee Pages)
echo -e "${YELLOW}→ 推送到 Gitee (Gitee Pages 自动触发)...${NC}"
git push gitee main
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Gitee 推送成功${NC}"
    echo -e "   ${GREEN}→ Gitee Pages 地址: https://zhao-nancheng.gitee.io/ai-news-hub/${NC}"
else
    echo -e "${RED}✗ Gitee 推送失败${NC}"
    echo -e "${YELLOW}⚠️  请确保已添加 Gitee 远程仓库${NC}"
    echo -e "${YELLOW}⚠️  运行: git remote add gitee <你的gitee仓库地址>${NC}"
fi
echo ""

# 7. 显示部署状态
echo "=========================================="
echo "  部署完成"
echo "=========================================="
echo ""
echo "📊 部署状态:"
echo ""
echo "🌍 国际访问:"
echo "   https://ai-news-hub-rosy.vercel.app/"
echo ""
echo "🇨🇳 国内访问:"
echo "   https://zhao-nancheng.gitee.io/ai-news-hub/"
echo ""
echo "📝 查看部署日志:"
echo "   Vercel: https://vercel.com/zhao-nancheng-s-projects"
echo "   Gitee: https://gitee.com/zhao-nancheng/ai-news-hub/pages"
echo ""
echo "✅ 双平台同步部署完成！"
echo "完成时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
