#!/bin/bash

# AI News 自动更新脚本 v4.0
# 整合：新闻抓取 + 论文推荐 + 热点总结 + 历史归档

set -e

# 配置
PROJECT_DIR="/data1/cc/vide-coding/ai-news-hub"
NEWS_DIR="$PROJECT_DIR/docs/news"
PAPERS_DIR="$PROJECT_DIR/docs/papers"
WEEKLY_DIR="$PROJECT_DIR/docs/weekly"
DATE=$(date +"%Y-%m-%d")
DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
TIMESTAMP=$(date +%s)

export PROJECT_DIR NEWS_DIR PAPERS_DIR DATE DATETIME

echo "=========================================="
echo "  AI News 自动更新开始 (v4.0 整合版)"
echo "=========================================="
echo "时间: $DATETIME"
echo ""

# 创建目录
mkdir -p "$NEWS_DIR"
mkdir -p "$PAPERS_DIR"
mkdir -p "$WEEKLY_DIR"

echo "📰 Step 1: 增强版多源抓取（Enhanced）..."
python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/fetch-enhanced.py

echo ""
echo "📚 Step 2: 抓取 arXiv AI 论文..."
python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/fetch-arxiv-papers.py

echo ""
echo "📊 Step 3: 更新首页索引..."
python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/update-homepage.py

echo ""
echo "🔄 Step 4: 推送到 GitHub + GitLab..."
cd "$PROJECT_DIR"

# 添加所有更改
git add docs/news/ docs/papers/ docs/latest-news.md

# 获取文件行数
NEWS_LINES=$(wc -l < "$NEWS_DIR/$DATE.md" 2>/dev/null || echo "0")
PAPERS_LINES=$(wc -l < "$PAPERS_DIR/$DATE.md" 2>/dev/null || echo "0")

# 提交更改
COMMIT_MSG="Auto-update: AI News briefing - $DATE

- News: $NEWS_LINES lines
- Papers: $PAPERS_LINES lines
- Homepage: Updated
- Timestamp: $TIMESTAMP
- Auto-generated by ai-news-hub v4.0"

git commit -m "$COMMIT_MSG"

# 推送到 GitHub
echo "推送到 GitHub..."
git push origin master

echo ""
echo "推送到 GitLab..."
git push gitlab master || echo "⚠️  GitLab 推送失败（可能是网络问题）"

echo ""
echo "✅ 成功推送到远程仓库！"
echo "Vercel 将自动检测并重新部署..."

echo ""
echo "=========================================="
echo "  自动更新完成！"
echo "=========================================="
echo "完成时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
