#!/bin/bash

# AI News Minimal Auto-Update Script
# Creates a placeholder news file to ensure cron doesn't fail
# Full content will be added when sources are available

set -e

# Configuration
PROJECT_DIR="/data1/cc/vide-coding/ai-news-hub"
NEWS_DIR="$PROJECT_DIR/docs/news"
DATE=$(date +"%Y-%m-%d")
DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
TIMESTAMP=$(date +%s)
NEWS_FILE="$NEWS_DIR/$DATE.md"

echo "=========================================="
echo "  AI News Minimal Auto-Update"
echo "=========================================="
echo "Date: $DATE"
echo "Time: $DATETIME"
echo ""

# Guard (2026-10-01): skip if today's news file already has real content.
# Prevents the 22:00/02:00 cron from clobbering real briefings
# (e.g. fetched by the OpenClaw news job) with a placeholder.
if [ -f "$NEWS_FILE" ] && [ "$(wc -c < "$NEWS_FILE")" -gt 2000 ]; then
    echo "✅ Today's news file already has real content: $NEWS_FILE ($(wc -c < "$NEWS_FILE") bytes)"
    echo "Skipping placeholder overwrite. Nothing to do."
    exit 0
fi

# Create directory
mkdir -p "$NEWS_DIR"

# Create minimal news file
cat > "$NEWS_FILE" << EOF
# 📰 Daily AI & Tech News Briefing

**Date**: $DATE
**Status**: Automated update pending
**Coverage**: Last 48 hours

---

## ⏳ Update in Progress

Daily AI news briefing is being generated.

**System Status**: Automated news fetching is being optimized for reliability.

**What's Happening**:
- News sources are being fetched
- Content is being curated and categorized
- Full briefing will be available shortly

---

## 📊 System Information

- **Update Time**: $DATETIME
- **Timestamp**: $TIMESTAMP
- **Next Update**: Tomorrow 02:00
- **Mode**: Minimal (placeholder)

---

**Note**: This is an automated placeholder. Full news coverage will be restored once the fetching system is optimized. The system is transitioning to use more reliable data sources.

---

**Generated on**: $DATETIME
**Auto-generated by**: ai-news-hub (Minimal Mode)
EOF

echo "📝 News file created: $NEWS_FILE"
echo "   Size: $(wc -c < "$NEWS_FILE") bytes"
echo ""

# Git operations
echo "🔄 Committing to git..."
cd "$PROJECT_DIR"

git add "docs/news/$DATE.md" || echo "⚠️  Git add failed"

COMMIT_MSG="Auto-update: AI News briefing - $DATE (Minimal placeholder)

- Status: Placeholder file created
- Timestamp: $TIMESTAMP
- Auto-generated by ai-news-hub (Minimal Mode)
- Note: Full content will be added when sources are available"

git commit -m "$COMMIT_MSG" 2>&1 || echo "⚠️  Git commit failed (no changes?)"

# Push to GitHub
echo "🚀 Pushing to GitHub..."
if git push origin main 2>&1; then
    echo "✅ Pushed to GitHub successfully"
else
    echo "⚠️  GitHub push failed"
fi

echo ""
echo "=========================================="
echo "  Auto-Update Complete!"
echo "=========================================="
echo "Finished: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
