#!/bin/bash

# AI News 自动更新脚本 v5.0
# 重新分类：行业动态 + 研究前沿 + 热门推荐

set -e

# 配置
PROJECT_DIR="/data1/cc/vide-coding/ai-news-hub"
NEWS_DIR="$PROJECT_DIR/docs/news"
INDUSTRY_FILE="$PROJECT_DIR/docs/industry.md"
RESEARCH_FILE="$PROJECT_DIR/docs/research.md"
TRENDING_FILE="$PROJECT_DIR/docs/trending.md"
DATE=$(date +"%Y-%m-%d")
DATETIME=$(date +"%Y-%m-%d %H:%M:%S")
TIMESTAMP=$(date +%s)

export PROJECT_DIR NEWS_DIR DATE DATETIME

echo "=========================================="
echo "  AI News 自动更新开始 (v5.0 重新分类版)"
echo "=========================================="
echo "时间: $DATETIME"
echo ""

# 创建目录
mkdir -p "$NEWS_DIR"

echo "📰 Step 1: 抓取行业动态（TechCrunch 等）..."
# python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/fetch_industry_news.py
echo "⚠️  行业动态抓取脚本待实现"
echo "📝 更新 docs/industry.md"

echo ""
echo "🔬 Step 2: 抓取 arXiv 研究论文..."
python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/fetch_arxiv_news.py

echo ""
echo "🔥 Step 3: 更新热门推荐..."
# python3.9 /data1/cc/vide-coding/ai-news-hub/scripts/update_trending.py
echo "⚠️  热门推荐更新脚本待实现"
echo "📝 更新 docs/trending.md"

echo ""
echo "📊 Step 4: 更新研究前沿页面..."
echo "📝 更新 docs/research.md"

echo ""
echo "🔄 Step 5: 推送到 GitHub + GitLab..."
cd "$PROJECT_DIR"

# 添加所有更改
git add docs/news/ docs/industry.md docs/research.md docs/trending.md

# 获取文件行数
NEWS_LINES=$(wc -l < "$NEWS_DIR/$DATE.md" 2>/dev/null || echo "0")

# 提交更改
COMMIT_MSG="Auto-update: AI News briefing - $DATE

- News: $NEWS_LINES lines
- Industry: Updated
- Research: Updated
- Trending: Updated
- Timestamp: $TIMESTAMP
- Auto-generated by ai-news-hub v5.0"

git commit -m "$COMMIT_MSG" || echo "⚠️  没有新的更改需要提交"

# 推送到 GitHub
echo "推送到 GitHub..."
git push origin main || echo "⚠️  GitHub 推送失败（可能是网络问题）"

echo ""
echo "推送到 GitLab..."
git push gitlab main || echo "⚠️  GitLab 推送失败（可能是网络问题）"

echo ""
echo "✅ 成功推送到远程仓库！"
echo "Vercel 将自动检测并重新部署..."

echo ""
echo "=========================================="
echo "  自动更新完成！"
echo "=========================================="
echo "完成时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
